version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - run: pnpm install
      - run:
          command: pnpm nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: pnpm install
      - nx/set-shas
      - run: pnpm nx-cloud start-ci-run --stop-agents-after="build"

      - run: pnpm nx-cloud record -- pnpm nx format:check
      - run: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3 & pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci & pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
workflows:
  build:
    jobs:
      - agent:
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main
