name: CI
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "*.md"

env:
  # Database
  DATABASE_URL: file:./ci.db

  # Clerk
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
  CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /app
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /app

  # Upstash
  UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
  UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.8"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.2"

      - name: Install dependencies
        run: bun install

      - name: Check format
        run: bun run format:check

      - name: Check lint
        run: bun run lint

      - name: Build
        run: bun run build
